config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include,path
from recipe2 import views
from member import views
from .import views as config_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipe2/', include('recipe2.urls')),
    path('member/',include('member.urls')),
    path('', config_views.index),
    path('stock/', include('stockapp.urls')),
    path('mypage/',include('mypage.urls')),
]

member/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'member'

urlpatterns = [
    path('login/',
    auth_views.LoginView.as_view(
        template_name='member/login.html'
    ),
    name='login'    
    ),
    path('logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
        ),
    path('signup/',views.signup, name='signup'),
    path('static/', views.static),
    path('index/',views.index,name='index'),
    path('home/',views.home, name='home'),
    path('check/',views.check)
    ]

recipe2/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='recipe2'
urlpatterns = [
    path('search/', views.SearchFormView.as_view(), name = 'search'),
    #path('recommend/', views.RecipeStockAPIView.as_view(), name = 'recommend'),
    # path('recommend/', views.RandomAPIView.as_view(), name = 'recommend'),
    path('recommend/', views.recipeStock, name = 'recommend'),

]

stockapp/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = 'stockapp'

urlpatterns = [
  path('add/', views.add, name='add'),
  path('stock/', views.stock, name='stock'),
  path('stock/delete/<int:stock_id>/', views.delete, name='delete'),
  ]


# from django.urls import path, include
# from .views import StockView, StockDetailView

# app_name = 'stockapp'

# urlpatterns = [
#     path('stock/', StockView.as_view(), name='stock_list'),
#     path('stock/<int:stock_id>/', StockDetailView.as_view(), name='stock_detail')
#     # path('stock/<int:pk>/', stock_detail, name='stock_detail'),
# ]

stockapp/models.py
from distutils.text_file import TextFile
from operator import mod
from pickle import TRUE
from django.db import models
from django.db.models.fields import CharField, IntegerField, FloatField
from django.db.models.fields import DateField
# from ingredient.models import Ingredient
from django.contrib.auth.models import User

from member.models import Member



class Add(models.Model):
  
    Add_user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Add_username = CharField(max_length=10, null=True)
    # user_name = models.CharField(max_length=10, null=True)
    Add_stock = CharField(max_length=10, null=True)
    Add_amount = CharField(max_length=4, null=True)
    Add_month = DateField()

    class Meta:
        db_table = 'Add'
        app_label = 'stockapp'

class Stock(models.Model):

    stock_user = models.ForeignKey(User, on_delete=models.CASCADE,db_column='user_user_id')
    
    stock_stock = models.CharField(max_length=10, null=True)
    stock_amount = models.CharField(max_length=4, null=True)
    stock_month = DateField()
    stock_urls = models.URLField(max_length=255)
    class Meta:
      db_table = 'Stock'
      app_label = 'stockapp'
    # managed = False

stockapp/views.py
from ast import Add
from asyncio.windows_events import NULL
from operator import length_hint
from ssl import MemoryBIO
from django.forms import DateTimeField
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.models import User
from member.models import Member
from .models import Add ,Stock


def add(request):
  if request.user.is_authenticated:
    if request.method == 'POST':

      Member = User.objects.get(username=request.user.username)
      
      Add_stock = request.POST.get('Add_stock')
      Add_amount = request.POST.get('Add_amount')
      Add_month = request.POST.get('Add_month')
      url_start = 'https://www.coupang.com/np/search?component=&q='
      url_end = '&channel=user'
      url_all = url_start + Add_stock + url_end
      
      if len(Add_month) == NULL:
        return render(request, 'stockapp/add.html',{})
      else:
        add = Add(Add_stock=Add_stock, Add_amount=Add_amount,Add_month=Add_month,Add_user=Member)
        stock = Stock(stock_stock=Add_stock, stock_amount=Add_amount,stock_month=Add_month,stock_urls=url_all,stock_user=Member)
        add.save()
        stock.save()

        return render(request, 'stockapp/message.html',{}) 
    return render(request, 'stockapp/add.html', {})
  else:
    return render(request,'member/login.html')

# def stock(request):
#   stock_list = Stock.objects.filter(stock_user=User.objects.get(username=request.user.username))
#   return render(request,'stockapp/stock.html',{'stock_list': stock_list})


def stock(request):
  if request.user.is_authenticated:
    stock_list = Stock.objects.filter(stock_user=User.objects.get(username=request.user.username))
    return render(request,'stockapp/stock.html',{'stock_list': stock_list})
  else:
    return render(request,'member/login.html')


def delete(request, stock_id):
    data = Stock.objects.get(id=stock_id)
    data.delete()
    return render(request, 'stockapp/message2.html',{}) 

# User.objects.get(username=request.user.username)


# from rest_framework.views import APIView
# from rest_framework.response import Response
# from rest_framework import status
# from .serializers import StockSerializer
# from .models import Stock
# from rest_framework import permissions


# class StockView(APIView):
#     def get(self, request):
#         queryset = Stock.objects.filter(user_id=request.user.id)
#         print(request.user.id)
#         serializer = StockSerializer(queryset, many=True)
#         return Response(serializer.data)

#     def post(self, request):
#         # _mutable = request.data._mutable
#         # request.data._mutable = True
#         # request.data.update({"user_id": request.user.id})
#         # request.data._mutable = _mutable
#         serializer = StockSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# class StockDetailView(APIView):
#     def get(self, request, stock_id):
#         # serializer = StockSerializer(data=request.data)
#         stock = Stock.objects.filter(id=stock_id)
#         if stock:
#             serializer = StockSerializer(stock, many=True)
#             return Response(serializer.data)
#         else:
#             return Response({'Error': "Can't find stock"}, status=status.HTTP_404_NOT_FOUND)

#     def put(self, request, stock_id):
#         stock = Stock.objects.get(id=stock_id)
#         if stock:
#             serializer = StockSerializer(stock, data=request.data)
#             if request.user.id != stock.user_id.id:
#                 return Response({'Error': "Not your stock"}, status=status.HTTP_400_BAD_REQUEST)
#             if serializer.is_valid():
#                 serializer.save()
#                 return Response(serializer.data, status=status.HTTP_201_CREATED)
#             else:
#                 return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
#         else:
#             return Response({'Error': "Can't find stock"}, status=status.HTTP_404_NOT_FOUND)

#     def delete(self, request, stock_id):
#         stock = Stock.objects.get(id=stock_id)
#         if stock:
#             if request.user.id != stock.user_id.id:
#                 return Response({'Error': "Not your stock"}, status=status.HTTP_400_BAD_REQUEST)
#             else:
#                 stock.delete()
#                 return Response(status=status.HTTP_204_NO_CONTENT)
#         else:
#             return Response({'Error': "Can't find stock"}, status=status.HTTP_404_NOT_FOUND)

stockapp/templates/stockapp/add.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Zero F</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/boot/assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/boot/css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="http://127.0.0.1:8000/">Zero F</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'member:logout' %}">{{ user.username }} (Logout)</a>
                            {% else %}
                            <a class="nav-link" href="{% url 'member:login' %}">LOG IN</a>
                            {% endif %}
                        </li>
                        
                        
                    </ul>
                    
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">재료 추가</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                      <form action="/stock/add/" method="post">
                        <p class="text-white-75">재료 이름 : <input type="text" name="Add_stock" /></p> 
                        <p class="text-white-75">재료 수량 : <input type="text" name="Add_amount" /></p>
                      
                      <label for="Add_month"><p class="text-white-75">유통 기한 : </label>
                      <input type="date" id="Add_month" name="Add_month"><br />
                      
                        {% csrf_token %}
                        <br />
                        <button class="btn btn-primary btn-xl">ADD</button> <a class="btn btn-primary btn-xl" href='{% url "stockapp:stock" %}'>MY STOCK</a>
                      </form>
                        {% comment %} <p class="text-white-75 mb-5">오늘 뭐 먹지?</p>
                        <a class="btn btn-primary btn-xl" href='{% url "stockapp:add" %}'>열려라 냉장고!</a>
                        <a class="btn btn-primary btn-xl" href='{% url "recipe2:search" %}'>열려라 레시피!</a> {% endcomment %}
                    </div>
                    
                </div>
            </div>
        </header>
        <!-- About-->

        <!-- Services-->

        <!-- Portfolio-->
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Call to action-->
    
        <!-- Contact-->

    </body>
</html>

stockapp/templates/stockapp/message.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Zero F</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/boot/assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/boot/css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href='http://127.0.0.1:8000/'>Zero F</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'member:logout' %}">{{ user.username }} (Logout)</a>
                            {% else %}
                            <a class="nav-link" href="{% url 'member:login' %}">LOG IN</a>
                            {% endif %}
                        </li>
                        
                        <li class="nav-item"><a class="nav-link" href='{% url "member:signup" %}'>SIGN UP</a></li>
                    </ul>
                    
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-center">
                        <h1 class="text-white font-weight-bold">재료 등록 완료</h1>
                        <a class="btn btn-primary btn-xl" href='{% url "stockapp:add" %}'>추가 등록</a>
                        <a class="btn btn-primary btn-xl" href='{% url "stockapp:stock" %}'>열려라 재료</a>
                        <hr class="divider" />
                    </div>

                    
                      
                </div>
            </div1>
        </header>
        <!-- About-->
       
        <!-- Services-->

        <!-- Portfolio-->
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Call to action-->
    
        <!-- Contact-->

    </body>
</html>

stockapp/templates/stockapp/message2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Zero F</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/boot/assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/boot/css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href='http://127.0.0.1:8000/'>Zero F</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'member:logout' %}">{{ user.username }} (Logout)</a>
                            {% else %}
                            <a class="nav-link" href="{% url 'member:login' %}">LOG IN</a>
                            {% endif %}
                        </li>
                        
                        <li class="nav-item"><a class="nav-link" href='{% url "member:signup" %}'>SIGN UP</a></li>
                    </ul>
                    
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-center">
                        <h1 class="text-white font-weight-bold">재료 삭제 완료</h1>
                        <a class="btn btn-primary btn-xl" href='{% url "stockapp:stock" %}'>추가 삭제</a>
                        <a class="btn btn-primary btn-xl" href='{% url "stockapp:add" %}'>재료 등록</a>
                        <hr class="divider" />
                    </div>

                    
                      
                </div>
            </div1>
        </header>
        <!-- About-->
       
        <!-- Services-->

        <!-- Portfolio-->
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Call to action-->
    
        <!-- Contact-->

    </body>
</html>

stockapp/templates/stockapp/modify.html
<html>
	<head><title>django Test</title></head>
	<body>
		<form method="post" class="post-form">
			{% csrf_token %}
			{{ form.as_p }}
			<button onclick="history.back();return false;">취소</button>
			<button type="submit">등록</button>
		</form>
	</body>
</html>

stockapp/templates/stockapp/stock.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Zero F</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/boot/assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/boot/css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="http://127.0.0.1:8000/">Zero F</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'member:logout' %}">{{ user.username }} (Logout)</a>
                            {% else %}
                            <a class="nav-link" href="{% url 'member:login' %}">LOG IN</a>
                            {% endif %}
                        </li>
                        
                    </ul>
                    
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">MY STOCK</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <h3>{% csrf_token %}</h3>
                        <hr>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <td class="col-lg bg-primary text-white-75"><b>재료</b></td>
                                    <td class="col-lg bg-primary text-white-75"><b>수량</b></td>
                                    <td class="col-lg bg-primary text-white-75"><b>유통기한</b></td>
                                    <td class="col-lg bg-primary text-white-75"><b>구매하러가기</b></td>
                                    <td class="col-lg bg-primary text-white-75"><b>삭제</b></td>
                                </tr>
                            </thead>
                            {% for stock in stock_list %}
                            
                            <tbody>
                                <tr>
                                    <td class="col-lg bg-white text-black-75">{{ stock.stock_stock }}</td>
                                    <td class="col-lg bg-white text-black-75">{{ stock.stock_amount }}</td>
                                    <td class="col-lg bg-white text-black-75">{{ stock.stock_month }}</td>
                                    <td class="col-lg bg-white text-black-75"> <a class="col-lg bg-white text-black-75" href="{{ stock.stock_urls }}" target="_blank">구매하러가기</a></td>
                                    <td class="col-lg bg-white text-black-75"> <a class="col-lg bg-white text-black-75" href="delete/{{ stock.id }}">삭제</a></td>
                                </tr>
                            </tbody>
                            {% endfor %}
                    
                        </table>
                        <a class="btn btn-primary btn-xl" href='{% url "stockapp:add" %}'>재료 추가</a>
                        <a class="btn btn-primary btn-xl" href='{% url "recipe2:recommend" %}'>레시피 추천 받기</a>
                        {% comment %} <p class="text-white-75 mb-5">오늘 뭐 먹지?</p>
                        <a class="btn btn-primary btn-xl" href='{% url "stockapp:add" %}'>열려라 냉장고!</a>
                        <a class="btn btn-primary btn-xl" href='{% url "recipe2:search" %}'>열려라 레시피!</a> {% endcomment %}
                    </div>

    </body>
</html>